# Site settings
title: Jia-Hou Poh
description: Personal website for Jia-Hou Poh
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jia-Hou Poh, Ph.D.
user_description: 
user_title: Cognitive Neuroscientist
email: jiahou.poh@gmail.com
twitter_username: JiaHou_Poh
github_username:  JiaHou-Poh
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
